export const DEMO = 'DEMO';

// system menu
export const GET_SYSTEM_MENUS = 'GET_SYSTEM_MENUS';
export const SET_SYSTEM_MENUS_STATUS_BY_URL = 'SET_SYSTEM_MENUS_STATUS_BY_URL';
export const SET_SYSTEM_MENU_OPEN_KEYS = 'SET_SYSTEM_MENU_OPEN_KEYS';
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const HIDE_PAGE_HEADER = 'HIDE_PAGE_HEADER';
export const SHOW_PAGE_HEADER = 'SHOW_PAGE_HEADER';
export const HIDE_SIDE_BAR = 'HIDE_SIDE_BAR';
export const SHOW_SIDE_BAR = 'SHOW_SIDE_BAR';
